### ISSUE TITLE
example里也给个hide和move的例子吧~

### ISSUE THREAD

**Issue by Ken-u** [WittBulter/react-native-smartbar#5]
如题,通过navigator后在其他的子页面怎么再hide啊

**Comment by WittBulter** [comment]
好的，我再完善一些例子

**Comment by WittBulter** [comment]
我看了一下，你可能是不理解页面通信。
如果没有使用任何的数据管理方式，你可以把`this.tabbar`对象传入到下个页面，具体你可以参考react组件通信文档，有很多种不同的方法。
如果使用redux或是其他数据管理方案，则可以在全局store上新建一个对象控制。

**Comment by Ken-u** [comment]
这个知道。。。但是不觉得每次都这样传很麻烦么。。而且建议增加navigator，有另一个项目就是哇 😅

**Comment by WittBulter** [comment]
所以你需要一个数据通信的管理方式啊，tabbar只做了很小的一件事，如果连navigator都一起绑定了，未免侵入性太强了。
我建议你试试redux。
如果你更换到其他任何的数据管理方案上，会发现其实轻量级比较好控制，各个组件之间也不会因为路由显得粘滞和强耦合。

**Comment by Ken-u** [comment]
好的，谢谢~
